name: "Unit tests"

on:
  pull_request:
    branches: [mxc]
  push:
    branches: [mxc]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - uses: actions/checkout@v3
        with:
          repository: MXCzkEVM/mxc-geth

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Lint
        run: make lint

      - name: Test
        env:
          ANDROID_HOME: ""
          MXC_TEST: true
        run: make test
